apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: {{ .Values.api.image }}
        command: ["/bin/sh", "-c"]
        args:
          - pip install flask psycopg2-binary && python /app/app.py
        ports:
        - containerPort: {{ .Values.api.port }}
        envFrom:
        - secretRef:
            name: {{ .Values.secretName }}
        volumeMounts:
        - name: code
          mountPath: /app
      volumes:
      - name: code
        configMap:
          name: {{ .Values.codeConfigMap }}
